---
version: "3.8"
services:
  noscroll:
    build:
      context: .
      network: host
    image: noscroll:latest
    container_name: noscroll
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-group: squidscroll-django
        awslogs-create-group: "true"