# Generated by Django 3.0.8 on 2020-08-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200809_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelativeScoring',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.BigIntegerField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='relative_score',
            field=models.BigIntegerField(default=0),
        ),
    ]
