# Generated by Django 3.1.1 on 2020-09-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200812_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='link',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
